### PR TITLE
Ftr: Add integration test multi-server support

### PR DESCRIPTION
**Pull request by EnableAsync**
Support custom integration tests how to start by editing path/to/example/build/test.sh

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

**Review by zhaoyunxing92 — APPROVED** [review]
approved these changes

**Comment by AlexStocks** [comment]
merge it forcefully

**Review by LaurenceLiZhixin — APPROVED** [review]

**Comment by LaurenceLiZhixin** [comment]
Pls fix your ci check

**Comment by EnableAsync** [comment]
> Pls fix your ci check

Thank you for your review.
CI failed because the code used in CI was the version before multi-zone bug was fixed.

**Review by AlexStocks — APPROVED** [review]

**Comment by LaurenceLiZhixin** [comment]
This ci check relies on latest tag 1.5.7-rc1, which has multizone bug and cause the ci failed.. Bug is fixed in 1.5 branch.

**Pull request merged**
